pmd/pmd-regression-tester

- lib/pmdtester/builders/diff_builder.rb
- lib/pmdtester/builders/html_report_builder.rb
- resources/css/maven-base.css
- resources/css/maven-theme.css
The style of the report refers to https://djydewang.github.io/diffReport_Issue5154/findbugs-with-excldues/index.html
> Add HtmlReportBuilder to PmdTester

- .rubocop_todo.yml
- lib/pmdtester/builders/diff_builder.rb
- lib/pmdtester/parsers/projects_parser.rb
- test/integration_test_pmd_report_builder.rb
- test/test_cmd.rb
- test/test_diff_builder.rb
- test/test_html_report_builder.rb
- test/test_options.rb
- test/test_projects_parser.rb
Style/Documentation cop: http://rubocop.readthedocs.io/en/latest/cops_style/#styledocumentation
> Fix rubocop Style/Documentation offenses

- lib/pmdtester/builders/diff_builder.rb
- lib/pmdtester/builders/diff_report_builder.rb
- lib/pmdtester/builders/html_report_builder.rb
- lib/pmdtester/builders/pmd_report_builder.rb
- lib/pmdtester/builders/summary_report_builder.rb
- lib/pmdtester/pmd_branch_detail.rb
- lib/pmdtester/project.rb
- lib/pmdtester/runner.rb
- test/resources/summary_report_builder/branch_info.json
- test/resources/summary_report_builder/expected_index.html
- test/test_diff_builder.rb
- test/test_diff_report_builder.rb
- test/test_html_report_builder.rb
- test/test_pmd_branch_detail.rb
- test/test_runner.rb
- test/test_summary_report_builder.rb
The summary report [demo](https://djydewang.github.io/summary).
> Add SummaryReportBuilder to PmdTester

- .rubocop_todo.yml
- lib/pmdtester/builders/diff_builder.rb
- lib/pmdtester/builders/diff_report_builder.rb
- lib/pmdtester/builders/pmd_report_builder.rb
- lib/pmdtester/builders/summary_report_builder.rb
- lib/pmdtester/parsers/options.rb
- lib/pmdtester/pmd_branch_detail.rb
- lib/pmdtester/project.rb
- lib/pmdtester/runner.rb
- test/integration_test_runner.rb
- test/test_diff_report_builder.rb
- test/test_options.rb
- test/test_pmd_branch_detail.rb
- test/test_projects_parser.rb
- test/test_runner.rb
- test/test_summary_report_builder.rb
- Fix defual vlaue of webview url
- Add report_diff attribute to the Project class
- Finish online mode
I'v upload a baseline demo to [sourceforge](https://sourceforge.net/projects/pmd/files/pmd-regression-tester/) :smile:
> Add online mode for PmdTester

- lib/pmdtester/builders/summary_report_builder.rb
- lib/pmdtester/project.rb
- lib/pmdtester/report_diff.rb
- test/resources/summary_report_builder/expected_index.html
- test/test_diff_builder.rb
- test/test_summary_report_builder.rb
The new summary report demo: https://djydewang.github.io/summary/index-7-8.html
> Add 'introduce new errors' table head for html summary report

- lib/pmdtester/builders/diff_report_builder.rb
- test/resources/html_report_builder/expected_diff_report_index.html
- test/resources/html_report_builder/test_html_report_builder_patch.xml
> Render stack traces properly

- lib/pmdtester/builders/summary_report_builder.rb
- lib/pmdtester/pmd_branch_detail.rb
- pmdtester.gemspec
- test/resources/summary_report_builder/branch_info.json
- test/resources/summary_report_builder/expected_index.html
- test/test_pmd_branch_detail.rb
> Add the JDK version and locale info to the summary table of the diff report

- lib/pmdtester/builders/pmd_report_builder.rb
- lib/pmdtester/parsers/options.rb
- lib/pmdtester/runner.rb
- test/test_options.rb
> Support multithreaded execution of PMD

- Rakefile
- lib/pmdtester/builders/pmd_report_builder.rb
- pmdtester.gemspec
> Display a simple progress report every 2 minutes

- ruby.yml
I think this might be nice. It uses the default template for ruby projects
> [ci] Add github actions to execute ruby tests

- README.rdoc
- lib/pmdtester/builders/pmd_report_builder.rb
- lib/pmdtester/builders/project_builder.rb
- lib/pmdtester/parsers/options.rb
- lib/pmdtester/runner.rb
- pmdtester.gemspec
- test/integration_test_pmd_report_builder.rb
- test/resources/pmd7-config.xml
- test/resources/project-test.xml
- test/test_options.rb
- test/test_pmd_report_builder.rb
- test/test_project_builder.rb
- test/test_runner.rb
Enabling this option sets PMD_JAVA_OPTS before executing PMD.
Refs pmd/pmd#2885 and pmd/pmd#2901
> Add new option "--error-recovery"

- README.rdoc
- lib/pmdtester/parsers/options.rb
- lib/pmdtester/runner.rb
- test/test_options.rb
First step for using a different location: make it configurable
> Add new configuration option "--baseline-download-url"

- lib/pmdtester/builders/pmd_report_builder.rb
- pmdtester.gemspec
- resources/css/pmd-tester.css
- resources/js/code-snippets.js
- resources/js/project-report.js
- test/test_pmd_report_builder.rb
Creating elements using dom methods lets the browser escape the text content.
> Fix html escaping in code snippets

- .github/workflows/build.yml
- .github/workflows/manual-integration-tests.yml
- History.md
- test/integration_test_runner.rb
- test/manual_integration_tests.rb
- test/resources/integration_test_pmd_report_builder/project-test.xml
- test/resources/integration_test_runner/project-list-single.xml
- test/resources/integration_test_runner/project-list.xml
- test/resources/integration_test_runner/project-test.xml
Fixes #96 
Once https://github.com/pmd/pmd/pull/3666 is merged, this needs to be updated once more.
> Update integration tests

- History.md
- resources/css/pmd-tester.css
- resources/js/code-snippets.js
> Improve code snippet preview

- History.md
- resources/js/project-report.js
> Display length changing input control

- History.md
- resources/js/project-report.js
> Only register click handler on real rows

- History.md
- lib/pmdtester/parsers/pmd_report_document.rb
- pmdtester.gemspec
- test/test_pmd_report_document.rb
> Fix ruleset filter by language

- History.md
- lib/pmdtester/builders/pmd_report_builder.rb
- test/test_pmd_report_builder.rb
> Disable progress bar for PMD 7

- lib/pmdtester/parsers/pmd_report_document.rb
- lib/pmdtester/project.rb
- test/resources/pmd_report_document/sample_report_relativized_paths.xml
- test/test_pmd_report_document.rb
- test/test_project.rb
> Use relative paths without leading slash

- History.md
- lib/pmdtester/builders/pmd_report_builder.rb
- pmdtester.gemspec
- test/test_pmd_report_builder.rb
> Support new PMD 7 binary dist filename

- History.md
- README.rdoc
- lib/pmdtester/builders/project_hasher.rb
- test/resources/summary_report_builder_issue121/base-report.xml
- test/resources/summary_report_builder_issue121/base_branch_info.json
- test/resources/summary_report_builder_issue121/expected_base_data.js
- test/resources/summary_report_builder_issue121/expected_patch_data.js
- test/resources/summary_report_builder_issue121/expected_project_data.js
- test/resources/summary_report_builder_issue121/patch-report.xml
- test/resources/summary_report_builder_issue121/patch_branch_info.json
- test/resources/summary_report_builder_issue121/project-list.xml
- test/test_summary_report_builder.rb
> Escape violation messages

- History.md
- lib/pmdtester/runner.rb
- test/manual_integration_tests.rb
- test/resources/manual_integration_tests/expected_patch_config_3.xml
- test/resources/manual_integration_tests/patch_test_case_1_disable_AbstractClassWithoutAbstractMethod.patch
- test/resources/manual_integration_tests/patch_test_case_2_disable_AvoidMessageDigestField.patch
- test/resources/manual_integration_tests/patch_test_case_3_modify_pmd-core.patch
- test/resources/manual_integration_tests/patch_test_case_4_modify_docs.patch
- test/test_runner.rb
The patches needed to be adapted to the final PMD 7 changes.
> Fix manual integration tests

- .github/workflows/publish-release.yml
- checkout was missing
- for gh cli, also specify repository
> chore(ci): Fix public-release workflow
